# Configuración del sitio
title: Sergio Rios
description: Desarrollador Full Stack con 8+ años de experiencia
author: Sergio Rios
email: srios0e@gmail.com
url: "https://sriosgit.github.io" # Cambia esto por tu URL de GitHub Pages

# Configuración de Jekyll
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Configuración de colecciones
collections:
  projects:
    output: true
    permalink: /proyectos/:title/

# Configuración de páginas
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Sergio Rios"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "Sergio Rios"

# Configuración de social media
social:
  github: sriosgit
  linkedin: sergiorioscab
  email: srios0e@gmail.com

# Configuración de navegación
navigation:
  - title: Inicio
    url: /
  - title: Proyectos
    url: /proyectos/
  - title: Blog
    url: /blog/
  - title: Sobre Mí
    url: /sobre-mi/ 